# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_config',
            name='jenkins',
        ),
    ]
