# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0002_remove_project_config_jenkins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_config',
            name='k8s',
        ),
    ]
