# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0003_remove_project_config_k8s'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config',
            name='jenkins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='OpsManage.Jenkins_Assets'),
        ),
        migrations.AddField(
            model_name='project_config',
            name='k8s',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='OpsManage.K8s_Assets'),
        ),
    ]
