# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0007_auto_20180804_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_config',
            name='service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='OpsManage.Service_Assets'),
        ),
        migrations.AlterUniqueTogether(
            name='project_config',
            unique_together=set([('project_env', 'project', 'service')]),
        ),
    ]
