# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0008_auto_20180804_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_config',
            unique_together=set([('project_env', 'project')]),
        ),
    ]
