# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0010_auto_20180804_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_config',
            name='project_service',
        ),
    ]
