# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0012_auto_20180804_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x90\x8d\xe7\xa7\xb0')),
                ('image_name', models.CharField(max_length=200, verbose_name=b'docker\xe9\x95\x9c\xe5\x83\x8f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('image_version', models.CharField(max_length=50, verbose_name=b'docker\xe9\x95\x9c\xe5\x83\x8f\xe7\x89\x88\xe6\x9c\xac\xe5\x8f\xb7')),
                ('is_online', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe4\xb8\x8a\xe7\xba\xbf\xe6\x88\x96\xe5\x9b\x9e\xe6\xbb\x9a')),
                ('run_env', models.CharField(max_length=20, verbose_name=b'\xe8\xbf\x90\xe8\xa1\x8c\xe7\x8e\xaf\xe5\xa2\x83')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe7\x9a\x84\xe7\x94\xa8\xe6\x88\xb7')),
                ('create_time', models.CharField(max_length=25, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'opsmanage_deploy_record',
                'verbose_name': '\u4ee3\u7801\u53d1\u5e03\u8bb0\u5f55',
                'verbose_name_plural': '\u4ee3\u7801\u53d1\u5e03\u8bb0\u5f55',
            },
        ),
    ]
