# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0013_deploy_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_project_config',
            options={'permissions': (('can_read_log_project_config', '\u8bfb\u53d6\u9879\u76ee\u90e8\u7f72\u65e5\u5fd7\u6743\u9650'), ('can_change_log_project_config', '\u66f4\u6539\u9879\u76ee\u90e8\u7f72\u65e5\u5fd7\u6743\u9650'), ('can_add_log_project_config', '\u6dfb\u52a0\u9879\u76ee\u90e8\u7f72\u65e5\u5fd7\u6743\u9650'), ('can_delete_log_project_config', '\u5220\u9664\u9879\u76ee\u90e8\u7f72\u65e5\u5fd7\u6743\u9650')), 'verbose_name': '\u9879\u76ee\u914d\u7f6e\u64cd\u4f5c\u8bb0\u5f55\u8868', 'verbose_name_plural': '\u9879\u76ee\u914d\u7f6e\u64cd\u4f5c\u8bb0\u5f55\u8868'},
        ),
    ]
