# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0014_auto_20180809_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_assets',
            old_name='project_address',
            new_name='service_pom_path',
        ),
        migrations.RemoveField(
            model_name='service_assets',
            name='project_repo_passwd',
        ),
        migrations.RemoveField(
            model_name='service_assets',
            name='project_repo_user',
        ),
        migrations.AddField(
            model_name='service_assets',
            name='service_root_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
