# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManage', '0015_auto_20180828_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config',
            name='project_replication',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x89\xaf\xe6\x9c\xac\xe6\x95\xb0'),
        ),
    ]
