# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_order',
            name='order_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u53d1\u884c\u7248\u672c\u53f7'),
        ),
    ]
